BulletinBoard/BulletinBoard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BulletinBoard/app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import PostsList, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, Responses, AcceptResponse, DeclineResponse, DeleteResponse
app_name = 'app'

urlpatterns = [
    path('', PostsList.as_view(), name='feed'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'), # Ссылка на детали поста
    path('add/', PostCreateView.as_view(), name='post_create'), # Ссылка на создание поста
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post_update'), # Ссылка на редактирование поста
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'), # Ссылка на удаеление поста
    path('responses/', Responses.as_view(), name='responses'),
    path('responses/<int:pk>/accept', AcceptResponse, name='accept_response'),
    path('responses/<int:pk>/decline', DeclineResponse, name='decline_response'),
    path('responses/<int:pk>/delete', DeleteResponse, name='delete_response'),     
]

BulletinBoard/app/templates/layout/parts/footer.html
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
      <span class="text-muted">Ostap Moskalenko Footer</span>
    </div>
   </footer>

BulletinBoard/app/templates/layout/parts/header.html
<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>
   
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" class="nav-link px-2 text-secondary">Лента объявлений</a></li>
          {% if user.is_authenticated %}
          <li><a href="/responses" class="nav-link px-2 text-white">Мои объявления</a></li>
          {% endif %}
        </ul>
       
        <div class="text-end">
            
            {% if user.is_authenticated %}
                <a href="/"><button type="button" class="btn btn-light me-2">Личный кабинет (@{{request.user}})</button></a> 
                <a href="/accounts/logout"><button type="button" class="btn btn-outline-light me-2">Выйти</button></a>
                <a href="{% url 'app:post_create' %}"><button type="button" class="btn btn btn-success me-2">Создать обявление</button></a>
            {% else %}
                <a href="/accounts/login"><button type="button" class="btn btn-outline-light me-2">Войти</button></a>
                <a href="/accounts/signup"><button type="button" class="btn btn-warning">Регистрация</button></a>    
            {% endif %}
        </div>
      </div>
    </div>
   </header>