BulletinBoard/BulletinBoard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BulletinBoard/app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import PostsList, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, Responses, AcceptResponse, DeclineResponse, DeleteResponse
app_name = 'app'

urlpatterns = [
    path('', PostsList.as_view(), name='feed'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'), # Ссылка на детали поста
    path('add/', PostCreateView.as_view(), name='post_create'), # Ссылка на создание поста
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post_update'), # Ссылка на редактирование поста
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'), # Ссылка на удаеление поста
    path('responses/', Responses.as_view(), name='responses'),
    path('responses/<int:pk>/accept', AcceptResponse, name='accept_response'),
    path('responses/<int:pk>/decline', DeclineResponse, name='decline_response'),
    path('responses/<int:pk>/delete', DeleteResponse, name='delete_response'),     
]

BulletinBoard/app/templates/app/feed.html
<!--  наследуемся от шаблона base.html -->
{% extends 'layout/base.html' %}

{% block title %}
Лента объявлений
{% endblock title %}

{% block content %}

<!-- {% load cache %} Загружаем кэширование -->
    <!-- {% cache 30 headerPosts %} Кэшируем отдельный блок на 30 секунд -->
<center><h1>Лента объявлений</h1></center>

    <!-- {% endcache %} -->

{% if posts %}



    {% for post in posts %}
    
    <!--Section: News of the day-->
<div class="row gx-5">
    <div class="col-md-6 mb-4">
        <div class="bg-image hover-overlay ripple shadow-2-strong rounded-5" data-mdb-ripple-color="light">
            <img src="{{ post.image.url}}" class="img-fluid" />
            <a href="#!">
                <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
            </a>
        </div>
    </div>

    <div class="col-md-6 mb-4">
        @{{post.user}} - {{ post.date_create|date:'d M Y' }}
        <h4><strong>{{ post.title }}</strong></h4>
        <span class="badge bg-success px-2 py-1 shadow-1-strong mb-3">{{ post.category }} </span>
        <p class="text-muted">
            {{ post.content|truncatechars:150}}
        </p>
        <p>Всего откликов: <span class="badge bg-success me-3">{{ post.number_of_comments }}</span></p>
        <a href="{% url 'app:post_detail' post.id %}">
            <!-- здесь
                news -- название приложения, которое задано в urls.py с помощью директивы app_name,
                post_detail -- название ссылки в списке эндпойнтов urlpatterns,
                post.id -- id объекта, который передаётся в качестве через эндпойнт и подставляется вместо <int:pk>
                    -->

            <button type="button" class="btn btn-primary">Смотреть полностью</button>
        </a>
        {% if user.is_authenticated %} 
        <a href="{% url 'app:post_update' post.id %}">
            <!-- здесь
                news -- название приложения, которое задано в urls.py с помощью директивы app_name,
                post_detail -- название ссылки в списке эндпойнтов urlpatterns,
                post.id -- id объекта, который передаётся в качестве через эндпойнт и подставляется вместо <int:pk>
                    -->

            <button type="button" class="btn btn-primary">Редактировать</button>
        </a>
        <a href="{% url 'app:post_delete' post.id %}">
            <!-- здесь
                news -- название приложения, которое задано в urls.py с помощью директивы app_name,
                post_detail -- название ссылки в списке эндпойнтов urlpatterns,
                post.id -- id объекта, который передаётся в качестве через эндпойнт и подставляется вместо <int:pk>
                    -->

            <button type="button" class="btn btn-danger"">Удалить</button>
        </a>
        {% endif %}
    </div>

</div>
    {% endfor %}
</table>

<!-- Заменили код пагинатора на подключение шаблона с этим кодом -->
{% include 'app/parts/paginator.html' %}

{% else %}
<!-- Если продуктов нет, то сообщаем об этом пользователю  -->
<h2>Объявлений нет!</h2>
{% endif %}
{% endblock content %}

BulletinBoard/app/templates/app/post_create.html
{% extends 'layout/base.html' %}
{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}

<div class="card mb-3">
    <img src="{{ post.image.url}}" class="card-img-top" alt=""/>
    <div class="card-body">
        <h6 class="text-muted">@{{ post.user.username }} - {{ post.category }}</h6>
        <h5 class="card-title">{{ post.title }}</h5>
    
      <p class="card-text">
        {{ post.content }}
      </p>
      <p class="card-text">
        <small class="text-muted">{{ post.date_create|date:'d M Y h:m' }}</small>
      </p>
    </div>
  </div>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
      <!-- Теперь нам нужна только готовая форма и кнопка -->
      
      <input class="btn btn-success" type="submit" value="Опубликовать">
   </form>

{% endblock content %}

BulletinBoard/app/templates/app/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="css/style.css">
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<title></title>
</head>
<body>
<div class="card mb-3">
    <img src="http://127.0.0.1:8000/media/{{post.image.name}}" class="card-img-top" style="max-width:500px" alt="{{ post.title }}"/>
    <div class="card-body">
        <h6 class="text-muted">@{{ post.user.username }} - {{ post.category }}</h6>
        <h5 class="card-title">{{ post.title }}</h5>
    
      <p class="card-text">
        {{ post.content }}
      </p>
      <p class="card-text">
        <small class="text-muted">{{ post.date_create|date:'d M Y h:m' }}</small>
      </p>
    </div>
  </div>
</body>
</html>

BulletinBoard/app/templates/app/post_delete.html
{% extends 'layout/base.html' %}
{% block title %}
Удаление поста
{% endblock title %}

{% block content %}

<h3>Удалить данное объявление?</h3>
<div class="card mb-3">
    <img src="{{ post.image.url}}" class="card-img-top" alt="{{ post.title }}"/>
    <div class="card-body">
        <h6 class="text-muted">@{{ post.user.username }} - {{ post.category }}</h6>
        <h5 class="card-title">{{ post.title }}</h5>
    
      <p class="card-text">
        {{ post.content }}
      </p>
      <p class="card-text">
        <small class="text-muted">{{ post.date_create|date:'d M Y h:m' }}</small>
      </p>
    </div>
  </div>
<form method="POST">
 {% csrf_token %}
   <input class="btn btn-success" type="submit" value="Delete">
</form>

{% endblock content %}

BulletinBoard/app/templates/app/post_detail.html
{% extends 'layout/base.html' %}
{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}

<div class="card mb-3">
    <img src="{{ post.image.url}}" class="card-img-top" alt="{{ post.title }}"/>
    <div class="card-body">
        <h6 class="text-muted">@{{ post.user.username }} - {{ post.category }}</h6>
        <h5 class="card-title">{{ post.title }}</h5>
    
      <p class="card-text">
        {{ post.content }}
      </p>
      <p class="card-text">
        <small class="text-muted">{{ post.date_create|date:'d M Y h:m' }}</small>
        <small class="text-muted">Всего откликов - {{ post.number_of_comments }}</small>
        
      </p>
    </div>
  </div>

<section style="background-color: #eee;">
  <div class="container py-3">

    <div class="row d-flex justify-content-center">
      <div class="col-md-8 col-lg-6 col-xl-10">

        <div class="card">
          <div class="card-header d-flex justify-content-between align-items-center p-3"
            style="border-top: 4px solid #ffa900;">
            <h5 class="mb-0">Комментарии</h5>
            <div class="d-flex flex-row align-items-center">
              <span class="badge bg-warning me-3">{{ post.number_of_comments }}</span>
            </div>
          </div>
          <div class="card-body" data-mdb-perfect-scrollbar="true" style="position: relative; ">

            {% for comment in comments%}
            <div class="d-flex justify-content-between">
              <p class="small mb-1">{{ comment.user }}</p>
              <p class="small mb-1 text-muted">{{ comment.date_create }}</p>
            </div>
            <div class="d-flex flex-row justify-content-start">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava5-bg.webp"
                alt="avatar 1" style="width: 45px; height: 100%;">
              <div>
                <p class="small p-2 ms-3 mb-3 rounded-3" style="background-color: #f5f6f7;">
                  {{ comment.message }}</p>
              </div>            
            </div>
            {% endfor%}
            {% if user.is_authenticated %}
            
                      <div class="card-footer text-muted d-flex justify-content-start align-items-center p-3">
            <div class="input-group mb-0">
              
              <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{ comment_form }}
                    <button class="btn btn-info" type="submit">Опубликовать комментарий <i class="fas fa-comments"></i></button>
                </div>
            </form>
            
            </div>
          </div>
            

            {% else %}
            <a href="/accounts/login"><button type="button" class="btn btn-warning me-2">Войти</button></a>
            <a href="/accounts/signup"><button type="button" class="btn btn-warning me-2">Регистрация</button></a>   
            {% endif %}
          </div>
        </div>
      </div>
    </div>

  </div>
</section>





  

{% endblock content %}

BulletinBoard/app/templates/app/post_response.html
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <!-- Теперь нам нужна только готовая форма и кнопка -->

    <input class="btn btn-success" type="submit" value="Опубликовать">
</form>

{% endblock content %}

BulletinBoard/app/templates/app/post_update.html
{% extends 'layout/base.html' %}
{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}

<div class="card mb-3">
    <img src="{{ post.image.url}}" class="card-img-top" alt=""/>
    <div class="card-body">
        <h6 class="text-muted">@{{ post.user.username }} - {{ post.category }}</h6>
        <h5 class="card-title">{{ post.title }}</h5>
    
      <p class="card-text">
        {{ post.content }}
      </p>
      <p class="card-text">
        <small class="text-muted">{{ post.date_create|date:'d M Y h:m' }}</small>
      </p>
    </div>
  </div>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
      <!-- Теперь нам нужна только готовая форма и кнопка -->
      
      <input class="btn btn-success" type="submit" value="Сохранить">
   </form>

{% endblock content %}

BulletinBoard/app/templates/app/response_accepted_email.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="css/style.css">
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<title></title>
</head>
<body>
    <div class="card">
        <div class="card-header">
            Привет, {{userName}}! Ваш отклик принят автором!
        </div>
        <div class="card-body">
            <h5 class="card-title">Объявление: {{post.title}}</h5>
            <p class="card-text">Автор обявления от {{post.user}}</p>
            <p class="card-text">{{response.message}}</p>
            <a href="http://127.0.0.1:8000/{{post.id}}" class="btn btn-primary">Перейти</a>
        </div>
    </div>
</body>
</html>

BulletinBoard/app/templates/app/response_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="css/style.css">
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<title></title>
</head>
<body>
    <div class="card">
        <div class="card-header">
            Привет, {{userName}}! У вас новый отклик!
        </div>
        <div class="card-body">
            <h5 class="card-title">Объявление: {{post.title}}</h5>
            <p class="card-text">Отклик от {{response.user}}</p>
            <p class="card-text">{{response.message}}</p>
            <a href="http://127.0.0.1:8000/{{post.id}}" class="btn btn-primary">Перейти</a>
        </div>
    </div>
</body>
</html>

BulletinBoard/app/templates/app/response_declined_email.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="css/style.css">
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<title></title>
</head>
<body>
    <div class="card">
        <div class="card-header">
            Привет, {{userName}}! Ваш отклик отклонен автором!
        </div>
        <div class="card-body">
            <h5 class="card-title">Объявление: {{post.title}}</h5>
            <p class="card-text">Автор обявления от {{post.user}}</p>
            <p class="card-text">{{response.message}}</p>
            <a href="http://127.0.0.1:8000/{{post.id}}" class="btn btn-primary">Перейти</a>
        </div>
    </div>
</body>
</html>

BulletinBoard/app/templates/app/responses.html
<!--  наследуемся от шаблона base.html -->
{% extends 'layout/base.html' %}


{% block title %}
Управление моими публикациями
{% endblock title %}

{% block content %}

<!-- {% load cache %} Загружаем кэширование -->
    <!-- {% cache 30 headerPosts %} Кэшируем отдельный блок на 30 секунд -->
<center><h1>Управление моими публикациями</h1></center>
<hr>

    <!-- {% endcache %} -->

{% if posts %}

<form method="GET">
    {{ filter.form }}
    <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы, придётся делать самим -->
    <input class="btn btn-info" type="submit" value="Найти">
</form>
<hr>

    {% for post in filter.qs %}
    
    <!--Section: News of the day-->
<div class="row gx-5">
    <div class="col-md-6 mb-4">
        <div class="bg-image hover-overlay ripple shadow-2-strong rounded-5" data-mdb-ripple-color="light">
            <img src="{{ post.image.url}}" class="img-fluid" />
            <a href="#!">
                <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
            </a>
        </div>
    </div>

    <div class="col-md-6 mb-4">
        @{{post.user}} - {{ post.date_create|date:'d M Y' }}
        <h4><strong>{{ post.title }}</strong></h4>
        <span class="badge bg-success px-2 py-1 shadow-1-strong mb-3">{{ post.category }} </span>
        <p class="text-muted">
            {{ post.content|truncatechars:150}}
        </p>
        <p>Всего откликов: <span class="badge bg-success me-3">{{ post.number_of_comments }}</span></p>
        <a href="{% url 'app:post_detail' post.id %}">
            <!-- здесь
                news -- название приложения, которое задано в urls.py с помощью директивы app_name,
                post_detail -- название ссылки в списке эндпойнтов urlpatterns,
                post.id -- id объекта, который передаётся в качестве через эндпойнт и подставляется вместо <int:pk>
                    -->

            <button type="button" class="btn btn-primary">Смотреть полностью</button>
        </a>
        {% if user.is_authenticated %} 
        <a href="{% url 'app:post_update' post.id %}">
            <!-- здесь
                news -- название приложения, которое задано в urls.py с помощью директивы app_name,
                post_detail -- название ссылки в списке эндпойнтов urlpatterns,
                post.id -- id объекта, который передаётся в качестве через эндпойнт и подставляется вместо <int:pk>
                    -->

            <button type="button" class="btn btn-primary">Редактировать</button>
        </a>
        <a href="{% url 'app:post_delete' post.id %}">
            <!-- здесь
                news -- название приложения, которое задано в urls.py с помощью директивы app_name,
                post_detail -- название ссылки в списке эндпойнтов urlpatterns,
                post.id -- id объекта, который передаётся в качестве через эндпойнт и подставляется вместо <int:pk>
                    -->

            <button type="button" class="btn btn-danger"">Удалить</button>
        </a>
        {% endif %}
    </div>

</div>
<hr>
{% if post.number_of_comments > 0 %}

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Пользователь</th>
        <th scope="col">Дата</th>
        <th scope="col">Сообщение</th>
        <th scope="col">Дата ответа на отклик</th>
        <th scope="col">Действия</th>
      </tr>
    </thead>
    <tbody>
{% for comment in post.getComments%}
      <tr>
        <th scope="row">1</th>
        <td>{{comment.user}}</td>
        <td>{{comment.date_create}}</td>
        <td>{{comment.message}}</td>
        <td>{{comment.date_accepted}}</td>
        <td>{% if comment.isAccepted %}
            <a href="{% url 'app:decline_response' comment.id %}">
                <button type="button" class="btn btn-danger">Отменить отклик</button>
            </a>
        {% else %}
        <a href="{% url 'app:accept_response' comment.id %}">
            <button type="button" class="btn btn-success">Принять отклик</button>
        </a>
        {% endif %}
        <a href="{% url 'app:delete_response' comment.id %}">
            <button type="button" class="btn btn-danger">Удалить отклик</button>
        </a>
        </td>
      </tr>
{% endfor %}
{% else %}
<p class="text-muted">
    Откликов пока нет
</p>
{% endif %}
</tbody>
</table>

    {% endfor %}
</table>

<!-- Заменили код пагинатора на подключение шаблона с этим кодом -->
{% include 'app/parts/paginator.html' %}

{% else %}
<!-- Если продуктов нет, то сообщаем об этом пользователю  -->
<h2>Объявлений нет!</h2>

{% endif %}
{% endblock content %}